### ISSUE TITLE
gradle-credential-helper plugin v.slow to configure in project with many subprojects

### ISSUE THREAD

**Issue by Naitbit** [GoogleCloudPlatform/artifact-registry-maven-tools#26]
After adding `com.google.cloud.artifactregistry.gradle-plugin` to `settings.gradle.kts` in my project configuration time skyrocketed from ~4 to ~40 seconds.
Gradle scans displays that
com.google.cloud.artifactregistry.gradle-credential-helper takes ~37 seconds to configure.

(not download dependencies from artifact registry itself, they are already cached on my local machine, just the configuration step of plugin which happens on every build)

With:
![obraz](https://user-images.githubusercontent.com/4226039/77356279-e4f64980-6d3d-11ea-995e-49193c1cd397.png)

Without:
![obraz](https://user-images.githubusercontent.com/4226039/77356351-05260880-6d3e-11ea-8a61-03be66eacd02.png)

Credentials should come from `gcloud` (and in general it works but takes a long time)
Executing `gcloud config config-helper --format=json\(credential\)` manually in command line returns quickly
Time output:
 real	0m0,373s
user	0m0,339s
sys	0m0,036s

Is there something in `--debug` logs that can help investigating that?

**Comment by molian6** [comment]
Hello, it shouldn't take that long, have you also cached artifactregistry-auth-common too? The plugin is depend on it.
Meanwhile, could you provide the snippets of how did you use it in settings.gradle.kts?

**Comment by Naitbit** [comment]
settings.gradle.kts:
```kotlin
buildscript {
    repositories {
        maven { url = uri("https://plugins.gradle.org/m2/") }
    }
    dependencies {
        classpath("gradle.plugin.com.google.cloud.artifactregistry:artifactregistry-gradle-plugin:2.0.0")
    }
}

apply(plugin = "com.google.cloud.artifactregistry.gradle-plugin")
````
Just to be sure what do you mean cached artifactregistry-auth-common?
It exists in my local maven cache `caches/modules-2/files-2.1/com.google.cloud.artifactregistry/artifactregistry-auth-common/2.0.0`  if that is what you were asking.
I did run this build multiple times before reporting to make sure. I've also verified that this happens on multiple machines on 2 continents so it should not be machine/network specific. (In all cases it was using `gcloud` though, not sure if passing json via GOOGLE_APPLICATION_CREDENTIALS instead of gcloud would make that problem to go away).

**Comment by molian6** [comment]
Hello,

Yes I was asking about "artifactregistry-auth-common/2.0.0" module, and it seems it is cached. It looks like something is slow on the gradle/gcloud. 
Are you run into this issue constantly, or it happens occasionally? The token are short lived for 60 mins. If you waited more than 60 min for your builds, it will trigger the gcloud to get a new access token, that may be slow.

Meanwhile, I'll try to reproduce your issue. Sorry for the inconvenience.

**Comment by molian6** [comment]
I unfortunately cannot reproduce this issue with the same scripts as you put inside settings.gradle.kts.

I would suggest try setup gcloud with other methods, like a [service account json key](https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account): 
`gcloud auth activate-service-account `

Or try setup [GOOGLE_APPLICATION_CREDENTIALS](https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable).

**Comment by Naitbit** [comment]
It happens on every build to me. No waiting for token expiration required.
Adding just GOOGLE_APPLICATION_CREDENTIALS variable did not help, though maybe I would have to logout/remove `gcloud` as it may have been defaulting to `gcloud` anyway (not sure what is prioritized by plugin if both are available).

@molian6 Does this plugin when applied to setting repeats auth for each gradle subproject/module by any chance? In project with just single `:app` configuration of this plugin is not that bad. (meaning same configuration in settings.gradle plugin configuration no longer takes more then the rest of the build and completes in less then a second)

**Comment by Naitbit** [comment]
Do I read that right that for **each** of the projects https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/blob/master/artifactregistry-gradle-plugin/src/main/java/com/google/cloud/artifactregistry/gradle/plugin/ArtifactRegistryGradlePlugin.java#L89
credentials are read and refreshed separately?  Does this have to happen this way? Wouldn't it possible to get credentials fetched/refreshed just once for given build?

**Comment by molian6** [comment]
Thanks for the feedback and taking time looking into this!
That is a good point that the credentials are fetched multiple times. We can possibly change that.

Would you mind providing us a bit more info about how the entire project is configured? e.g. how is the parent project, sub-project structured, what is your `build.gradle` file and `settings.gradle` looks like, and `init.gradle` if there's one?

If all of the release going to the same repository, a walk-around might be putting the plugin inside the `build.gradle` under the parent project. https://cloud.google.com/artifacts/docs/java/quickstart#config-gradle

**Comment by Naitbit** [comment]
Well we have :app that depends on a lot of `:feature: projects, that depends on some components and leaf util subprojects (65 android library projects and 15 java non-android project, but I doubt it matters for this case).
I don't have `init.gradle`.
We wanted to share one of those components with another project as `.aar` (and that part works)
but configuration times taking order of magnitude longer means that I have to remove this plugin from the project.
From what I checked it was not sufficient to set this plugin only in projects that were directly using .aar from ArtifactRegistry. I had to set it in all projects that had it as transitive dependency which was unfortunately about ~50 out of 80 so that would not solve the time issue (and would require a lot more boilerplate).
I suspect that creating hello world :app with dependencies to 100 empty subprojects  and adding
`apply(plugin = "com.google.cloud.artifactregistry.gradle-plugin")`  in `settings` would be enough to reproduce the issue.

**Comment by Naitbit** [comment]
Created repo that can reproduce the issue: https://github.com/Naitbit/ArtifactRegistryIssues

**Comment by molian6** [comment]
Hello,

Really appreciate your help for creating the projects that reproduce the issue, and your excellent suggestion. I've created the PR and it reduced the build time from 40s to 2s. We will keep you updated when the newer version is online.

Lian

**Comment by molian6** [comment]
The gradle plugin hasn't been released yet. so reopen. Close until released.

**Comment by molian6** [comment]
Hello,

The new gradle plugin is published. Feel free to try it out and let us know if there are any other issues. https://plugins.gradle.org/plugin/com.google.cloud.artifactregistry.gradle-plugin

Thank you again for helping investigating and providing us the test project.
Lian

**Comment by Naitbit** [comment]
Thanks. it helps :+1: .
Didn't found any new issues yet, but https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/issues/27 issue still exist.
