### ISSUE TITLE
Applying Android Plugin fails on Gradle 6

### ISSUE THREAD

**Issue by Naitbit** [GoogleCloudPlatform/artifact-registry-maven-tools#27]
With Gradle 6 building project fails with following message.
```
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.application']
   > com.google.common.base.Suppliers$NonSerializableMemoizingSupplier cannot be cast to java.util.function.Supplier
```
This can be reproduced in fe: following repo https://github.com/Naitbit/ArtifactRegistryIssues

**Comment by Naitbit** [comment]
Surprising part about this issue is that:
- it is Android application plugin that fails not the Artifact Registry Plugin.
App does build on Gradle 6.2 without Artifact Registry plugin though.

- Gradle Scan does not display deprecation warning for Artifact Registry Plugin.

**Comment by Naitbit** [comment]
@molian6 Did you have a chance to reproduce the issue on provided repository?
At some point Android developers will be forced to upgrade to Gradle 6+

**Comment by Naitbit** [comment]
Turns out that this happens because ArtifactRegistry imports 
`classpath 'com.google.guava:guava:27.1-android' // note the qualifier`
into buildscript classpath.

The workaround is to override it by adding manually 
`classpath("com.google.guava:guava:27.1-jre")`
dependency in affected project

AFAIK all projects with more then one module on Gradle 6+ will be affected when applying Artifact Registry plugin via settings.
Applying manually to each project though would probably cause huge configuration time due to variant of https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/issues/26

**Comment by loosebazooka** [comment]
yeah weirdly, `com.google.auth:google-auth-library-oauth2-http:0.16.2` is pulling in `com.google.guava:guava:27.1-android`. Perhaps both dependencies
`com.google.http-client:google-http-client` and `com.google.auth:google-auth-library-oauth2-http` should be updated to more recent versions in project `:artifactregistry-auth-common`
