### ISSUE TITLE
ArtifactRegistry plugin does not sync with Android Studio 4

### ISSUE THREAD

**Issue by Naitbit** [GoogleCloudPlatform/artifact-registry-maven-tools#31]
Project on it's own build by Gradle but Android Studio sync fails with
`Not a supported repository protocol 'artifactregistry': valid protocols are [http, https, file, gcs, s3, sftp]`

(This issue does not exist in Android Studio 3.6.x)

------

It seems that in Android Studio 4 sync 
root build.gradle
```groovy
allprojects {
    repositories {
        maven {
            url 'artifactregistry://us-west1-maven.pkg.dev/PROJECT_ID/REPOSITORY_ID'
        }
    }
}
```

is no long valid way of configuring plugin when Artifact Registry is applied in settings.gradle.

Applying plugin manually in each subproject build.gradle also failed for me.

Example project:
https://github.com/Naitbit/ArtifactRegistryIssues/tree/issue_31_as4_sync
Android Studio issue: https://issuetracker.google.com/issues/155352398

**Comment by Naitbit** [comment]
Android Studio 4 is now final. Problem still exist. Also verified that problem still exist on Gradle-6.5rc1.
Is there anything more I can do to help with this issue?

**Comment by findjigar** [comment]
Facing similar issue. Hoping to get some resolution on this soon

**Comment by Naitbit** [comment]
The workaround for me turned out to be to add `apply plugin: 'com.google.cloud.artifactregistry.gradle-plugin'` manually to all non-android (pure Java/Kotlin subprojects) in addition to applying plugin in settings.gradle.

I did not initially suggest that as it has horrible performance implications (fe: for me on 20 subprojects where I had to add it it added 13s of *configuration* time meaning that build took 16s instead of 3s due to seemingly requesting credentials from network 20 times on each build/configuration), but it seems that with Google Application Default Credentials.  https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools#authentication and 2.1.1  version performance is acceptable (below 1s impact)

**Comment by Gridasov** [comment]
Should be fixed by: 
https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/pull/51

**Comment by yihanzhen** [comment]
2.1.2 is released: https://plugins.gradle.org/plugin/com.google.cloud.artifactregistry.gradle-plugin

Please let us know if the fix helped.
