### ISSUE TITLE
Pulling artifacts in a container fails because artifact registry can not find default credentials

### ISSUE THREAD

**Issue by senyoAsamoah** [GoogleCloudPlatform/artifact-registry-maven-tools#34]
Summary:
Pulling an artifact from the registry during the gradle build process results in the error below when in a container.
```
An exception occurred applying plugin request [id: 'com.google.cloud.artifactregistry.gradle-plugin', version: '2.0.1']
> Failed to apply plugin [id 'com.google.cloud.artifactregistry.gradle-plugin']
   > Failed to get access token from gcloud or Application Default Credentials
```
Reproduction Steps:
1. Update the gradle-wrapper propeties file in you gradle project to use a version >= 6.0.1
2. in your build.gradle file ensure that you have add the artifact registry plugin and add your artifact repository to the repositories list with the credentials provided
3. Create a sample dockerfile manifest that uses the gradle commands  
4. Run docker build and verify that during the `gradle build` step gradle is able to successfully pull the artifact from the repository

**Comment by lindsayismith** [comment]
Thanks for the report.  We're thinking the simplest solution is to stop throwing an exception if no credentials can be found, instead simple log this and send none with any request.
