### ISSUE TITLE
Gradle: Not a supported repository protocol 'artifactregistry' in buildscript block

### ISSUE THREAD

**Issue by trietsch** [GoogleCloudPlatform/artifact-registry-maven-tools#40]
When using the Gradle plugin for Google Cloud Artifact Registry in the `buildscript` section of a `build.gradle.kts` / `build.gradle` file, the repository protocol `artifactregistry` is not found.

An example repo can be found [here](https://github.com/trietsch/gradle-gcp-artifact-registry). Clone the repository and run `./gradlew clean build`, and you'll be presented with the following error:

```
❯ ./gradlew clean build
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gradle-artifact-registry'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Not a supported repository protocol 'artifactregistry': valid protocols are [http, https, file, gcs, s3, sftp]
```

Removing the `maven("artifactregistry://...")` from the `buildscript` section works, however, I need to get a `classpath` dependency for the `buildscript` from my Maven Artifact Registry that resides in my GCP project. It seems that the plugin is not applied in the `buildscript` section. I have not found a way to do this, am I doing something wrong?

**Comment by loosebazooka** [comment]
I believe this is because the plugin is scoping it's repository additions to the `pluginManagement.repositories`, but not also `buildscript.repositories`. I'm testing a fix right now to see if that's true

**Comment by loosebazooka** [comment]
okay i think it got it, pushing a PR

**Comment by loosebazooka** [comment]
Can you test out this fix for me? It worked on my local instance, but probably not useful if it doesn't work for everyone.

1. clone this repo
2. ./gradlew install
3. add this to your project `settings.gradle.kts`
```
buildscript {
  repositories {
    mavenLocal()
    mavenCentral()
  }
  dependencies {
    classpath("com.google.cloud.artifactregistry:artifactregistry-gradle-plugin:2.1.2-SNAPSHOT2-SNAPSHOT")
  }
}

apply(plugin = "com.google.cloud.artifactregistry.gradle-plugin")
```
4. run your build

**Comment by trietsch** [comment]
Awesome! I'll try this out next week, when I've access to a laptop again 😁

**Comment by loosebazooka** [comment]
@trietsch any update here?

**Comment by trietsch** [comment]
Tomorrow I've got access to a laptop, I'll verify whether it works then and let you know :)

**Comment by trietsch** [comment]
Verified! It's working :) Thanks for the fix, this'll simplify a lot of Gradle scripts for me.

**Comment by loosebazooka** [comment]
Thanks for reporting and testing @trietsch!
