### ISSUE TITLE
'org.gradle.api.publish.maven.tasks.PublishToMavenRepository' property 'credentials.password' is missing an input or output annotation.

### ISSUE THREAD

**Issue by vonblanc** [GoogleCloudPlatform/artifact-registry-maven-tools#43]
Issue arises when running the PublishToMavenRepository task, with possible solutions:
    Reason: A property without annotation isn't considered during up-to-date checking (credentials.password).
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
     
Can these exceptions be somehow suppressed? 

com.google.cloud.artifactregistry.gradle-plugin:  2.1.1
gradle version: 7.0.2
Java version: 11

**Comment by jeffrey-lau-123** [comment]
+1 I started getting this error.
@vonblanc were you able to find a workaround to publish again?

**Comment by vonblanc** [comment]
@jeffrey-lau-123 I haven't yet, still stuck with the error, started after i upgraded plugin version. If you find a way around please let me know

**Comment by jeffrey-lau-123** [comment]
@vonblanc I ended up having to use password authentication following this guide and it started working https://cloud.google.com/artifact-registry/docs/java/authentication
I'm not sure how to get it to work again without having to do this :(

**Comment by vonblanc** [comment]
@jeffrey-lau-123 Thanks so much the credential helper wasn't working even with my google app env variable set up, used the basic auth as suggested. It's now working :). Seems like we must have auth

**Comment by lindsayismith** [comment]
Hi, this PR looks to fix this issue:

https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/pull/47

I'm closing this, please reopen if it did not fix it.  We will release a new version of the plugin that includes this in the near future.
