### ISSUE TITLE
Support for Gradle 7

### ISSUE THREAD

**Issue by Infeligo** [GoogleCloudPlatform/artifact-registry-maven-tools#52]
Currently this plugin does not work with Gradle 7 due to issues fixed in current snapshot by [this commit](https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/commit/d419bd303fce4da79bd193c840caa899845b9f90). I am using current snapshot without any problems, but this adds all the hassle of local build, adding local plugin repo, etc.

Can you release version 2.1.2 so that this fix would be available without any additional steps?

**Comment by lindsayismith** [comment]
Hi Mihhail, 

We will release a version soon, thanks for testing the fix.

**Comment by jkschneider** [comment]
@lindsayismith Any chance that patch release could be finalized? Thanks!

**Comment by yihanzhen** [comment]
Sorry for the delay - 2.1.2 here: https://plugins.gradle.org/plugin/com.google.cloud.artifactregistry.gradle-plugin

Please let us know if the fix helped!

**Comment by msm** [comment]
Confirmed working for me on gradle 7.1.1, thanks!
