### ISSUE TITLE
Dependency reference broken?

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/artifact-registry-maven-tools#60]
I'm not sure this PR changed something, but now this plugin relies on `artifactregistry-auth-common:2.1.3`, which is missing

```
A problem occurred configuring root project '***'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.google.cloud.artifactregistry:artifactregistry-auth-common:2.1.3.
   
   Required by:
         project : > gradle.plugin.com.google.cloud.artifactregistry:artifactregistry-gradle-plugin:2.1.3
```

I can find it here, but there is no `pom` file: https://repo1.maven.org/maven2/com/google/cloud/artifactregistry/artifactregistry-auth-common/2.1.3/

CC: @yihanzhen @lindsayismith @chanseokoh

_Originally posted by @tonyshkurenko in https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/issues/56#issuecomment-933401532_

**Comment by loosebazooka** [comment]
Seems to be a incomplete release? Or something weird going on?

**Comment by yihanzhen** [comment]
Yeah this must be me. I'll take a look today.

**Comment by yihanzhen** [comment]
2.1.4 should be good to use: https://repo.maven.apache.org/maven2/com/google/cloud/artifactregistry/artifactregistry-auth-common/2.1.4/
